### PR TITLE
Use address string in config instead in url

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/5117

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Can we remove the dash from the repo name? It is super odd to import packages that differ in import path and package name. That this is even possible is weird. Further, I was thinking if it makes sense to put service and client logic together and not have the separation as this never turned out to be beneficial.

**Comment by TheoBrigitte** [comment]
I'll bit the bullet and move this to the `credentiald` repo then. Also had this idea in the beginning but dropped it somehow.

Any preference for the folder structure? Otherwise I go with `github.com/giantswarm/credentiald/client`.

**Comment by xh3b4sd** [comment]
Sounds good.

**Comment by TheoBrigitte** [comment]
Killing this repo :fire:

**Pull request closed without merging**
