### PR TITLE
First version

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/5117

Provide a go HTTP Rest client for [crendetiald](https://github.com/giantswarm/credentiald) service.

`README.md` might need some more love.

Provided some code examples on how to use this client in [`client_test.go`](./client/client_test.go).

Had to use `dep` for dependencies, since go modules gave some errors here:
```
$ go mod init
go: creating new go.mod: module github.com/giantswarm/credentiald-client
$ go build ./client 
# github.com/giantswarm/credentiald-client/client
client/client.go:66:33: cannot use requestFunc (type func(string) (*"github.com/go-resty/resty".Response, error)) as type func(string) (*"github.com/giantswarm/microclient/vendor/github.com/go-resty/resty".Response, error) in argument to microclient.Do
client/client.go:73:2: cannot use response (type *"github.com/giantswarm/microclient/vendor/github.com/go-resty/resty".Response) as type *"github.com/go-resty/resty".Response in return argument
```

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
> Do I somehow miss something or is main() missing?

The goal is to have a client library that can be used by other project, so I didn't bother building a cli interface

> Also, I'm not sure what's going on, but it looks like dep didn't prune vendor directory properly. Any ideas?

Good point, I just ran `dep init` which apparently does not prune.

**Comment by tuommaki** [comment]
> The goal is to have a client library that can be used by other project, so I didn't bother building a cli interface

Ah, now that you say it's totally obvious. I somehow got so stuck in `README.md` section about how to build this and was wondering that when it points to package, there must be `main()` somewhere. All good.

**Comment by TheoBrigitte** [comment]
I am feeling lost with `dep`, running `dep prune` add all files which should be pruned (_test.go files, etc).
`dep ensure` does just nothing.

Prune settings are correct in the `Gopkg.toml`
```
[prune]
  go-tests = true
  unused-packages = true
```

Any idea?

**Comment by tuommaki** [comment]
Possibly `dep` version? I'm running `commit 22125cfaa6ddc71e145b1535d4b7ee9744fefff2` from `master` right now and for me it pruned whole lot of stuff. I was wondering though if it would also make sense to add `non-go = true` for pruning options? See https://golang.github.io/dep/docs/Gopkg.toml.html#prune

**Comment by TheoBrigitte** [comment]
Running `commit 22125cfaa6ddc71e145b1535d4b7ee9744fefff2` still give me the same results (add files instead of removing).

I also thought about adding `non-go = true` but the [doc](https://golang.github.io/dep/docs/Gopkg.toml.html#prune) says that it might not be safe, so I'll leave it out.

I think I'll go with what I have now.

**Pull request merged**
